//! Executes independent fixtures generated by scripts/verify_kernels.py.
use half::bf16;
use rsglang_core::{BatchPhase, Result, SequenceStep, StepBatch};
use rsglang_kernels::{CudaBackend, KernelBackend};
use serde_json::{json, Value};
fn values(v: &Value, name: &str) -> Vec<bf16> {
    v[name]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| bf16::from_f32(x.as_f64().unwrap() as f32))
        .collect()
}
fn main() -> Result<()> {
    let a: Vec<_> = std::env::args().collect();
    let v: Value = serde_json::from_slice(&std::fs::read(&a[1])?).unwrap();
    let b = CudaBackend::new(0)?;
    let norm_x = b.upload(&values(&v, "norm_x"), &[3, 133])?;
    let norm_w = b.upload(&values(&v, "norm_w"), &[133])?;
    let norm = b.rms_norm(&norm_x, &norm_w, 133, 1e-6)?;
    let x = b.upload(&values(&v, "linear_x"), &[3, 19])?;
    let w = b.upload(&values(&v, "linear_w"), &[7, 19])?;
    let linear = b.linear(&x, &w)?;
    let logits = b.logits(&x, &w)?;
    let gate = b.upload(&values(&v, "gate"), &[3, 133])?;
    let up = b.upload(&values(&v, "up"), &[3, 133])?;
    let swiglu = b.swiglu(&gate, &up)?;
    let add = b.add(&gate, &up)?;
    let batch = StepBatch {
        phase: BatchPhase::Prefill,
        sequences: vec![
            SequenceStep {
                request_id: 1,
                input_ids: vec![1; 5],
                start_pos: 17,
                pages: vec![2, 5],
                sampling: None,
            },
            SequenceStep {
                request_id: 2,
                input_ids: vec![2; 37],
                start_pos: 0,
                pages: vec![0, 8, 3],
                sampling: None,
            },
        ],
    };
    let meta = b.metadata(&batch, 16, 9, 3, 64)?;
    let emb = b.upload(&values(&v, "embedding"), &[3, 17])?;
    let embedded = b.embedding(&emb, &meta)?;
    let mut q = b.upload(&values(&v, "q"), &[42, 6 * 128])?;
    b.rope(&mut q, &meta, 6, 128, 1000000.)?;
    let k = b.upload(&values(&v, "k"), &[42, 2 * 128])?;
    let value = b.upload(&values(&v, "v"), &[42, 2 * 128])?;
    let mut kc = b.upload(&values(&v, "kc"), &[9, 16, 2, 128])?;
    let mut vc = b.upload(&values(&v, "vc"), &[9, 16, 2, 128])?;
    b.store_kv(&k, &value, &mut kc, &mut vc, &meta)?;
    let attn = b.attention(&q, &kc, &vc, &meta, 6, 2, 128)?;
    let last = b.last_hidden(&q, &meta)?;
    let routing = b.upload(&values(&v, "routing"), &[5, 7])?;
    let expert_input = b.upload(&values(&v, "expert_input"), &[5, 19])?;
    let mut routing_results = vec![];
    let mut mixtures = vec![];
    for normalize in [false, true] {
        let assignments = b.router_topk(&routing, 3, normalize)?;
        routing_results.push(
            assignments
                .iter()
                .map(|a| json!({"expert":a.expert,"rows":a.rows,"weights":a.weights}))
                .collect::<Vec<_>>(),
        );
        let mut acc = b.accumulator(5, 19)?;
        for assignment in &assignments {
            let mut output = b.gather_rows(&expert_input, &assignment.rows)?;
            for _ in 0..assignment.expert {
                output = b.add(&output, &output)?;
            }
            b.scatter_weighted(&mut acc, &output, assignment)?;
        }
        mixtures.push(b.download(&b.finish_accumulator(acc)?)?);
    }
    let fused = b.concat_rows(&[
        b.upload(&values(&v, "linear_w"), &[7, 19])?,
        b.upload(&values(&v, "linear_w"), &[7, 19])?,
    ])?;
    let joint = b.linear(&x, &fused)?;
    let parts = b.split_columns(&joint, &[7, 7])?;
    let repeated: Vec<_> = (0..11)
        .map(|_| b.upload(&values(&v, "linear_x"), &[3, 19]))
        .collect::<Result<_>>()?;
    let blocked = b.linear(&b.concat_rows(&repeated)?, &w)?;
    let result = json!({"blocked_linear":b.download(&blocked)?,"routing":routing_results,"mixtures":mixtures,"fused_split":parts.iter().map(|t|b.download(t)).collect::<Result<Vec<_>>>()?,"norm":b.download(&norm)?,"linear":b.download(&linear)?,"logits":(0..3).map(|r|b.download_logits_row(&logits,r)).collect::<Result<Vec<_>>>()?,"argmax":b.argmax(&logits)?,"swiglu":b.download(&swiglu)?,"add":b.download(&add)?,"embedding":b.download(&embedded)?,"rope":b.download(&q)?,"kc":b.download(&kc)?,"vc":b.download(&vc)?,"attention":b.download(&attn)?,"last":b.download(&last)?});
    std::fs::write(&a[2], serde_json::to_vec(&result).unwrap())?;
    b.synchronize()?;
    println!("GPU operator fixture exported");
    Ok(())
}
